select * from customer;
--Q1. What is the total revenue generated by male vs female customers

select gender, SUM(purchase_amount) as revenue 
from customer 
group by gender;

--Q2. Which customers used a discount but still spend more than the average purchase amount

select customer_id, purchase_amount 
from customer 
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

--Q3. Which are the top 5 products with the highest average review rating
select * from customer;
select item_purchased , DOUBLE(avg(review_rating::numeric),2) as Average Product Rating
from customer
group by it
order by item_purchased desc
limit 5;

--Q4. Compare the average purchase amounts between Standard and Express Shipping

select shipping_type,ROUND(avg(purchase_amount),2) AS "Average Purchase Amount"
from customer 
group by shipping_type
having shipping_type in ('Express','Standard');

--Q5. Do Subscribed customers spend more? Compare average spend and total revenue between
--subcribers and non-subscribers.

select ROUND(AVG(purchase_amount),2) as "Average Amount Spend",SUM(purchase_amount) as "Total Revenue",subscription_status
from customer
group by subscription_status;
--Q6. Which 5 products have the highest percentage of purchases with discounts applied.

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into new, Returning, and Loyal based on their total number of previous purchases, and
-- show the count of each segment.

with customer_type as (
select customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Rteurning'
	ELSE 'Loyal' 
	END as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Q8. What are the Top 3 most purchased products within each category.

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category order by count(customer_id)desc ) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select * from customer;

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5 
group by subscription_status;

--Q10. What is the revenue contribution of each age group.

select age_group,
sum(purchase_amount) as Total_Revenue
from customer 
group by age_group
order by Total_Revenue desc;

